#pragma once
#define ConnError "Fail to connect to Server!\n"
#define TimeoutError "Connection Time Out Error!\n"
#define DisconnError "Disonnection Error!\n"
#define CreateError "Thread Creation Error!\n"
#define BindError "Bind Error!\n"
#define VersError "Version Error!\n"
#define SendError "Send Message Error!\n"
#define RecvError "Receive Message Error!\n"
#define IDError "Sending object ID is invalid! Please input again:\n"
#define DataError "Sending data is out of range! Please input again:\n"
#define SUCCESS "Operation Success!\n"